# Generated by Django 2.2.5 on 2021-01-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Person',
        #     fields=[
        #         ('id', models.IntegerField(primary_key=True, serialize=False)),
        #         ('first_name', models.CharField(max_length=300)),
        #         ('last_name', models.CharField(max_length=300)),
        #         ('email', models.CharField(max_length=100)),
        #         ('gender', models.CharField(max_length=50)),
        #         ('school', models.CharField(max_length=300)),
        #         ('books', models.CharField(max_length=300)),
        #     ],
        #     options={
        #         'db_table': 'student_details',
        #     },
        # ),
    ]
