# Generated by Django 2.2.5 on 2021-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20210126_1805'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='School',
        #     fields=[
        #         ('REGIONID', models.IntegerField()),
        #         ('school', models.CharField(max_length=300, primary_key=True, serialize=False)),
        #         ('email', models.CharField(max_length=300)),
        #         ('principal', models.CharField(max_length=100)),
        #         ('phone', models.CharField(max_length=50)),
        #         ('address2', models.CharField(max_length=300)),
        #     ],
        #     options={
        #         'db_table': 'school_details',
        #     },
        # ),
    ]
