# Generated by Django 2.2.5 on 2021-01-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_school'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Book',
        #     fields=[
        #         ('title', models.CharField(max_length=300, primary_key=True, serialize=False)),
        #         ('author_name', models.CharField(max_length=300)),
        #         ('dop', models.CharField(max_length=100)),
        #         ('nop', models.CharField(max_length=50)),
        #     ],
        #     options={
        #         'db_table': 'book_details',
        #     },
        # ),
    ]
