# Generated by Django 2.2.5 on 2021-01-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_app', '0004_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=300)),
                ('dop', models.CharField(max_length=100)),
                ('nop', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'book_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('REGIONID', models.IntegerField()),
                ('school', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300)),
                ('principal', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'school_details',
                 'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=300)),
                ('books', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'student_details',
                 'managed': False,
            },
        ),
    ]
