# Generated by Django 2.2.5 on 2021-01-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_book_school_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
